name: GitHub Snake

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate GitHub Snake
        uses: Platane/snk@v2
        with:
          github_user: Flavia-crfaria
          width: 100
          height: 100
          theme: radical

